const state={platform:"todos",query:"",topic:"Todos",videos:[],books:[],resume:null,refreshing:false};
const grid=document.querySelector("#groups"),search=document.querySelector("#search"),sort=document.querySelector("#sort"),status=document.querySelector("#status"),refreshButton=document.querySelector("#refreshCatalog"),refreshStatus=document.querySelector("#refreshStatus");
const STORAGE_KEY="henry-vitrine-progress-v4",TOPIC_KEY="henry-vitrine-topic-v4";
const topicRules=[["altar","Altar"],["sacrifício","Altar"],["sacrificio","Altar"],["oração","Oração"],["oracao","Oração"],["orando","Oração"],["cura","Cura e Milagres"],["milagre","Cura e Milagres"],["ressurreição","Cura e Milagres"],["ressurreicao","Cura e Milagres"],["libertação","Libertação"],["libertacao","Libertação"],["maldição","Maldições e Família"],["maldicao","Maldições e Família"],["padrão familiar","Maldições e Família"],["familia","Família e Relacionamentos"],["família","Família e Relacionamentos"],["relacionamento","Família e Relacionamentos"],["fé","Fé"],["fe","Fé"],["profec","Profético"],["óleo","Unção e Óleo"],["oleo","Unção e Óleo"],["unção","Unção e Óleo"],["uncao","Unção e Óleo"],["bênção","Bênçãos"],["bencao","Bênçãos"]];
function clean(s=""){return String(s).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase()}
function esc(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function inferredTopic(v){if(v.segment)return v.segment;const text=clean([v.title,v.category,v.description,v.tags,v.channel].flat().join(" "));for(const [k,val] of topicRules)if(text.includes(clean(k)))return val;return v.category||"Ensino e Pregação"}
function platform(v){return String(v.platform||"youtube").toLowerCase()}
function label(v){return platform(v)==="youtube"?"YouTube":platform(v)==="facebook"?"Facebook":platform(v)==="instagram"?"Instagram":platform(v)==="tiktok"?"TikTok":"Fonte"}
function key(v){return platform(v)+":"+String(v.id||v.url||v.title)}
function dateOf(v){return v.published_at||v.upload_date||v.date||""}
function progress(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||"{}")}catch(_){return{}}}
function save(v,s){const p=progress();p[key(v)]={seconds:Number(s)||0,updatedAt:Date.now()};localStorage.setItem(STORAGE_KEY,JSON.stringify(p))}
function get(v){return progress()[key(v)]||null}
function fmt(s){s=Math.floor(s||0);return Math.floor(s/60)+":"+String(s%60).padStart(2,"0")}
function searchUrl(p,t){const q=encodeURIComponent("Henry Otasowere "+t);if(p==="facebook")return "https://www.facebook.com/search/videos/?q="+q;if(p==="instagram")return "https://www.instagram.com/explore/search/keyword/?q="+q;if(p==="tiktok")return "https://www.tiktok.com/search?q="+q;return "https://www.youtube.com/results?search_query="+q}
function segmentData(){const map=new Map();for(const v of state.videos){const s=inferredTopic(v);if(!map.has(s))map.set(s,{name:s,total:0,youtube:0,facebook:0,instagram:0,tiktok:0,latest:dateOf(v)});const x=map.get(s);x.total++;x[platform(v)]=(x[platform(v)]||0)+1;if(dateOf(v)>x.latest)x.latest=dateOf(v)}return [...map.values()].sort((a,b)=>String(b.latest).localeCompare(String(a.latest)))}
function renderSegments(){const board=document.querySelector("#segmentBoard");const data=segmentData();board.innerHTML=data.map(x=>'<button class="segment-card '+(state.topic===x.name?"active":"")+'" data-segment="'+esc(x.name)+'"><div class="segment-top"><span class="eyebrow">SEGMENTO</span><strong>'+esc(x.name)+'</strong></div><div class="segment-count">'+x.total+' vídeo(s)</div><div class="segment-platforms"><span>YT '+x.youtube+'</span><span>FB '+x.facebook+'</span><span>IG '+x.instagram+'</span><span>TT '+x.tiktok+'</span></div><small>Mais recentes primeiro ↘</small></button>').join("");board.querySelectorAll(".segment-card").forEach(b=>b.onclick=()=>{state.topic=b.dataset.segment;localStorage.setItem(TOPIC_KEY,state.topic);renderSegments();renderCategories();render()})}
function relevant(){let a=state.videos.filter(v=>{if(state.platform!=="todos"&&platform(v)!==state.platform)return false;const h=clean([v.title,v.segment,v.category,v.channel,v.description,v.tags].flat().join(" "));return !state.query||h.includes(clean(state.query))});if(state.topic!=="Todos")a=a.filter(v=>inferredTopic(v)===state.topic);if(sort.value==="title")a.sort((x,y)=>String(x.title).localeCompare(String(y.title)));else if(sort.value==="oldest")a.sort((x,y)=>String(dateOf(x)).localeCompare(String(dateOf(y))));else a.sort((x,y)=>String(dateOf(y)).localeCompare(String(dateOf(x))));return a}
function card(v){const p=get(v),resume=p&&p.seconds>5,thumb=v.thumbnail||"assets/youtube-placeholder.jpg";return '<article class="card"><button class="video-open" data-id="'+esc(key(v))+'"><div class="thumb" style="background-image:url('+encodeURI(thumb)+')"><span class="badge">'+label(v)+'</span>'+(resume?'<span class="resume-badge">▶ '+fmt(p.seconds)+'</span>':"")+'</div></button><div class="card-body"><h3>'+esc(v.title)+'</h3><div class="meta">'+esc(v.channel||"Canal")+" · "+esc(inferredTopic(v))+'</div><button class="watch" data-id="'+esc(key(v))+'">'+(resume?"▶ Continuar":"▶ Assistir")+"</button></div></article>"}
function booksFor(t){if(!t||t==="Todos")return state.books.slice(0,12);const q=clean(t);return state.books.filter(b=>clean([b.title,b.category,b.tags].flat().join(" ")).includes(q)||q.includes(clean(b.category||""))).slice(0,12)}
function book(b){return '<article class="book-card"><div class="book-cover">📖</div><div class="book-body"><span class="eyebrow">LIVRO</span><h4>'+esc(b.title)+'</h4><div class="meta">'+esc(b.category||"Biblioteca Profética")+'</div><a class="book-open" target="_blank" rel="noopener" href="'+encodeURI(b.url||"#")+'">Abrir livro</a></div></article>'}
function social(p,t){const names={youtube:"YouTube",facebook:"Facebook",instagram:"Instagram",tiktok:"TikTok"};return '<article class="social-search-card"><div class="social-icon">'+names[p][0]+'</div><div><span class="eyebrow">'+names[p]+'</span><h4>'+esc(t)+'</h4><p>Pesquisar vídeos do mesmo segmento.</p></div><a class="book-open" target="_blank" rel="noopener" href="'+searchUrl(p,t)+'">Abrir ↗</a></article>'}
function render(){const items=relevant(),t=state.topic;document.querySelector("#topicTitle").textContent=t==="Todos"?"Todos os conteúdos":t;document.querySelector("#topicPanel").hidden=t==="Todos";document.querySelector("#topicSummary").textContent=t==="Todos"?"":"Segmento: "+t;document.querySelector("#topicDescription").textContent=t==="Todos"?"Clique num segmento acima. Ele passa a ser a chave para reunir o mesmo assunto nas quatro redes.":"Aqui entram juntos os vídeos deste segmento. O padrão é sempre mais recente primeiro.";let html="";if(t!=="Todos"){html+='<section class="resource-section"><div class="section-title"><span class="eyebrow">VÍDEOS DO SEGMENTO</span><h3>'+esc(t)+'</h3><span>'+items.length+" catalogado(s)</span></div>"+(items.length?'<div class="grid">'+items.map(card).join("")+'</div>':'<div class="empty">Nenhum vídeo catalogado localmente neste segmento.</div>')+"</section>";html+='<section class="resource-section"><div class="section-title"><span class="eyebrow">MESMO SEGMENTO NAS 4 REDES</span><h3>Continuar a pesquisa</h3><span>Facebook · Instagram · TikTok · YouTube</span></div><div class="social-search-grid">'+["youtube","facebook","instagram","tiktok"].map(p=>social(p,t)).join("")+"</div></section>";const bs=booksFor(t);html+='<section class="resource-section"><div class="section-title"><span class="eyebrow">BIBLIOTECA PROFÉTICA</span><h3>Livros relacionados</h3><span>'+bs.length+'</span></div>'+(bs.length?'<div class="book-grid">'+bs.map(book).join("")+'</div>':'<div class="empty">Nenhum livro relacionado.</div>')+"</section>"}else html='<section class="resource-section"><div class="section-title"><span class="eyebrow">LINHA DO TEMPO</span><h3>Conteúdos recentes</h3><span>Mais recentes primeiro</span></div><div class="grid">'+items.map(card).join("")+"</div></section>";grid.innerHTML=html;status.textContent=items.length+" vídeo(s)";bind()}
function renderCategories(){const s=new Set(["Todos"]);state.videos.forEach(v=>s.add(inferredTopic(v)));document.querySelector("#categories").innerHTML=[...s].map(x=>'<button class="chip '+(x===state.topic?"active":"")+'" data-topic="'+esc(x)+'">'+esc(x)+"</button>").join("");document.querySelectorAll(".chip").forEach(b=>b.onclick=()=>{state.topic=b.dataset.topic;localStorage.setItem(TOPIC_KEY,state.topic);renderSegments();renderCategories();render()})}
function open(v){const p=get(v);if(p&&p.seconds>5){state.resume={v,p};document.querySelector("#resumeText").textContent="Você parou em "+fmt(p.seconds)+".";document.querySelector("#resumeModal").hidden=false}else launch(v,0)}
function launch(v,s){const u=s?((v.url||"")+(String(v.url).includes("?")?"&":"?")+"t="+Math.floor(s)+"s"):v.url;window.open(u,"_blank","noopener");save(v,s)}
function bind(){document.querySelectorAll("[data-id]").forEach(e=>e.onclick=()=>{const v=state.videos.find(x=>key(x)===e.dataset.id);if(v)open(v)})}
async function load(msg=false){if(msg){refreshButton.disabled=true;refreshStatus.textContent="Atualizando…"}try{const r=await fetch("videos.json?x="+Date.now(),{cache:"no-store"}),b=await fetch("books.json?x="+Date.now(),{cache:"no-store"});state.videos=await r.json();state.books=b.ok?await b.json():[];document.querySelector("#count-youtube").textContent=state.videos.filter(v=>platform(v)==="youtube").length+" vídeos";renderSegments();renderCategories();render();if(msg)refreshStatus.textContent="✓ Atualizado agora"}catch(e){if(msg)refreshStatus.textContent="Erro ao atualizar"}finally{if(msg){setTimeout(()=>refreshStatus.textContent="",3000);refreshButton.disabled=false}}}
search.oninput=()=>{state.query=search.value;render()};sort.onchange=render;document.querySelectorAll(".platform").forEach(b=>b.onclick=()=>{state.platform=b.dataset.platform;document.querySelectorAll(".platform").forEach(x=>x.classList.remove("active"));b.classList.add("active");render()});refreshButton.onclick=()=>load(true);document.querySelector("#clearTopic").onclick=()=>{state.topic="Todos";localStorage.setItem(TOPIC_KEY,"Todos");renderSegments();renderCategories();render()};document.querySelector("#heroPlay").onclick=()=>document.querySelector("#segmentBoard").scrollIntoView({behavior:"smooth"});document.querySelector("#resumeContinue").onclick=()=>{const x=state.resume;document.querySelector("#resumeModal").hidden=true;launch(x.v,x.p.seconds)};document.querySelector("#resumeRestart").onclick=()=>{const x=state.resume;document.querySelector("#resumeModal").hidden=true;launch(x.v,0)};state.topic=localStorage.getItem(TOPIC_KEY)||"Todos";load();
