const state={platform:"youtube",query:"",segment:"Todos",category:"Todos",videos:[]};
const grid=document.querySelector("#grid"),search=document.querySelector("#search"),sort=document.querySelector("#sort"),status=document.querySelector("#status");
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function repairText(value){let s=String(value??"");const map={"VÃ­deos":"V\u00eddeos","vÃ­deos":"v\u00eddeos","TÃ­tulo":"T\u00edtulo","catÃ¡logo":"cat\u00e1logo","CatÃ¡logo":"Cat\u00e1logo","publicitÃ¡rio":"publicit\u00e1rio","integraÃ§Ã£o":"integra\u00e7\u00e3o","aplicaÃ§Ã£o":"aplica\u00e7\u00e3o","NÃ£o":"N\u00e3o","nÃ£o":"n\u00e3o","vocÃª":"voc\u00ea","â€”":"\u2014","â€“":"\u2013","â€¦":"\u2026","âœ“":"\u2713","â™¡":"\u2661","â˜°":"\u2630","âŒ‚":"\u2302","âŒ•":"\u2315","â–¶":"\u25b6","�":" "};for(const [a,b] of Object.entries(map))s=s.split(a).join(b);return s}
const platforms={youtube:{label:"YOUTUBE",title:"V\u00eddeos de Henry Otasowere"},facebook:{label:"FACEBOOK",title:"V\u00eddeos do Minist\u00e9rio Voz da Cura"},tiktok:{label:"TIKTOK",title:"V\u00eddeos de Henry Otasowere"},instagram:{label:"INSTAGRAM",title:"V\u00eddeos de Henry Otasowere"}};
function clean(s){return repairText(s).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase()}
const rules=[["cura","Cura"],["curou","Cura"],["milagre","Cura"],["milag","Cura"],["oração","Oração"],["oracao","Oração"],["altar","Altar"],["liberta","Libertação"],["maldição","Maldições e Família"],["maldicao","Maldições e Família"],["familia","Família e Relacionamentos"],["família","Família e Relacionamentos"],["relacionamento","Família e Relacionamentos"],["profec","Profético"],["fé","Fé"],["fe ","Fé"],["bênção","Bênçãos"],["bencao","Bênçãos"]];
function segmentOf(v){if(v.segment)return repairText(v.segment);const t=clean([v.title,v.category,v.description,v.tags].flat().join(" "));for(const [k,s] of rules)if(t.includes(clean(k)))return s;return repairText(v.category||"Ensino e Pregação")}
function renderHeader(){document.querySelector("#platformEyebrow").textContent=platforms[state.platform].label;document.querySelector("#platformTitle").textContent=state.segment==="Todos" ? platforms[state.platform].title : "Segmento: "+state.segment}
function renderSegments(){const names=["Todos",...new Set(state.videos.map(segmentOf))];document.querySelector("#segments").innerHTML=names.map(s=>'<button class="chip '+(s===state.segment?"active":"")+'" data-segment="'+esc(s)+'">'+esc(s)+"</button>").join("");document.querySelectorAll("[data-segment]").forEach(b=>b.onclick=()=>{state.segment=b.dataset.segment;state.category="Todos";renderSegments();categories();render()})}
function categories(){const items=state.videos.filter(v=>v.platform===state.platform&& (state.segment==="Todos"||segmentOf(v)===state.segment));const cats=["Todos",...new Set(items.map(v=>repairText(v.category)).filter(Boolean))];document.querySelector("#categories").innerHTML=cats.map(c=>'<button class="chip '+(c===state.category?"active":"")+'" data-cat="'+esc(c)+'">'+esc(c)+"</button>").join("");document.querySelectorAll("[data-cat]").forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;categories();render()})}
function render(){renderHeader();let items=state.videos.filter(v=>{if(state.segment!=="Todos"&&segmentOf(v)!==state.segment)return false;if(state.platform!=="todos"&&v.platform!==state.platform)return false;const h=clean(repairText(v.title)+" "+repairText(v.category||""));return !state.query||h.includes(clean(state.query))});if(state.category!=="Todos")items=items.filter(v=>repairText(v.category||"").toLowerCase()===state.category.toLowerCase());if(sort.value==="title")items.sort((a,b)=>repairText(a.title).localeCompare(repairText(b.title)));else items.sort((a,b)=>(b.upload_date||b.published_at||"").localeCompare(a.upload_date||a.published_at||""));if(!items.length){grid.innerHTML='<div class="platform-empty"><h3>Nenhum vídeo catalogado neste segmento</h3><p>Quando houver vídeos verificados desta rede sobre '+esc(state.segment)+', eles aparecerão aqui.</p></div>';status.textContent="Nenhum vídeo";return}grid.innerHTML=items.map(v=>{const thumb=v.thumbnail||"";const badge=v.platform==="facebook"?"Facebook":v.platform==="tiktok"?"TikTok":v.platform==="instagram"?"Instagram":"YouTube";return '<article class="card"><button class="thumb-button" data-id="'+esc(v.id)+'"><div class="thumb" style="background-image:url(\''+esc(thumb)+'\')"><span class="badge">'+badge+'</span><span class="play-overlay">&#9654;</span></div></button><div class="card-body"><h3>'+esc(repairText(v.title))+'</h3><div class="meta">'+esc(repairText(v.channel||"Voz da Cura Network"))+" - "+esc(segmentOf(v))+'</div><button class="watch" data-id="'+esc(v.id)+'">&#9654; Assistir</button></div></article>'}).join("");status.textContent=items.length+" vídeos";grid.querySelectorAll("[data-id]").forEach(b=>b.onclick=()=>openVideo(state.videos.find(v=>v.id===b.dataset.id)))}
async function load(){status.textContent="A carregar catálogo...";try{const files=["videos.json","videos-facebook.json","videos-tiktok.json"];const rs=await Promise.all(files.map(f=>fetch(f+"?v=segment2",{cache:"no-store"})));if(rs.some(r=>!r.ok))throw new Error("Catálogos indisponíveis");const ds=await Promise.all(rs.map(r=>r.json()));state.videos=ds.flat();const counts={youtube:0,facebook:0,tiktok:0,instagram:0};state.videos.forEach(v=>counts[v.platform]=(counts[v.platform]||0)+1);for(const p of Object.keys(counts)){const e=document.querySelector("#count-"+p);if(e)e.textContent=counts[p]+" vídeos"}renderSegments();categories();render()}catch(e){grid.innerHTML='<div class="empty">Não foi possível carregar o catálogo.</div>';status.textContent="Catálogo indisponível";console.error(e)}}
function setPlatform(platform){state.platform=platform;state.category="Todos";document.querySelectorAll(".platform").forEach(b=>b.classList.toggle("active",b.dataset.platform===platform));categories();render();window.scrollTo({top:0,behavior:"smooth"})}
document.querySelectorAll(".platform").forEach(b=>b.onclick=()=>setPlatform(b.dataset.platform));search.oninput=()=>{state.query=search.value;render()};sort.onchange=render;
document.querySelectorAll(".bottom-item").forEach(b=>b.onclick=()=>{document.querySelectorAll(".bottom-item").forEach(x=>x.classList.remove("active"));b.classList.add("active");const a=b.dataset.bottom;if(a==="search"){search.focus();document.querySelector("#searchArea").scrollIntoView({behavior:"smooth",block:"center"})}else if(a==="home")window.scrollTo({top:0,behavior:"smooth"});else if(a==="favorites")status.textContent="Favoritos: selecione esta funcao quando a area de favoritos for ativada.";else document.querySelector("footer")?.scrollIntoView({behavior:"smooth"})});
load();