(function(){
const modal=document.querySelector("#playerModal"),playerWrap=document.querySelector("#playerWrap");
let currentVideo=null,attempt=0,loadTimer=null;
function closePlayer(){clearTimeout(loadTimer);modal.hidden=true;playerWrap.innerHTML="";document.body.classList.remove("player-open");currentVideo=null;attempt=0;}
function getTikTokId(v){const u=String(v?.url||"");const m=u.match(/\/video\/(\d+)/);if(m)return m[1];const m2=String(v?.id||"").match(/(\d{15,25})/);return m2?m2[1]:null;}
function loading(){playerWrap.innerHTML='<div class="player-loading" id="playerLoading"><div class="player-loading-text">A carregar o vídeo...</div></div>';}
function error(t){document.querySelector("#playerLoading")?.remove();const m=document.createElement("div");m.className="player-error";m.textContent=t;playerWrap.appendChild(m);}
function watch(v,kind){const f=document.querySelector("#mediaFrame"),l=document.querySelector("#playerLoading");if(!f)return;f.addEventListener("load",()=>{clearTimeout(loadTimer);l?.remove();f.style.visibility="visible";attempt=0},{once:true});clearTimeout(loadTimer);loadTimer=setTimeout(()=>{if(attempt<2){attempt++;if(kind==="facebook")openFacebook(v);else if(kind==="tiktok")openTikTok(v);else openYouTube(v);}else{l?.remove();f.style.visibility="visible";error("O vídeo não respondeu. A reprodução foi tentada novamente automaticamente.");}},10000);}
function openYouTube(v){const id=String(v.id);playerWrap.innerHTML='<div class="player-loading" id="playerLoading"><img src="https://i.ytimg.com/vi/'+encodeURIComponent(id)+'/hqdefault.jpg" alt="" loading="eager"><div class="player-loading-text">A carregar o vídeo...</div></div><iframe class="player-frame" id="mediaFrame" title="Vídeo YouTube" src="https://www.youtube-nocookie.com/embed/'+encodeURIComponent(id)+'?playsinline=1&rel=0&controls=1" allow="autoplay; encrypted-media; picture-in-picture; fullscreen" allowfullscreen></iframe>';watch(v,"youtube");}
function openFacebook(v){const href=String(v.url||"");if(!href){error("Vídeo do Facebook sem ligação válida.");return;}loading();const src="https://www.facebook.com/plugins/video.php?href="+encodeURIComponent(href)+"&show_text=false&width=560&height=315&allowfullscreen=true";playerWrap.innerHTML+='<iframe class="player-frame" id="mediaFrame" title="Vídeo Facebook" src="'+src+'" allow="autoplay; encrypted-media; picture-in-picture; fullscreen" allowfullscreen></iframe>';watch(v,"facebook");}
function openTikTok(v){const id=getTikTokId(v);if(!id){error("Vídeo do TikTok sem ID válido.");return;}loading();const src="https://www.tiktok.com/player/v1/"+id+"?controls=1&progress_bar=1&play_button=1&volume_control=1&fullscreen_button=1&timestamp=1&music_info=1&description=1&rel=0";playerWrap.innerHTML+='<iframe class="player-frame tiktok-frame" id="mediaFrame" title="Vídeo TikTok" src="'+src+'" allow="fullscreen; autoplay; encrypted-media" allowfullscreen></iframe>';watch(v,"tiktok");}
function openVideo(v){if(!v)return;currentVideo=v;attempt=0;modal.hidden=false;document.body.classList.add("player-open");const p=String(v.platform||"youtube").toLowerCase();if(p==="facebook")openFacebook(v);else if(p==="tiktok")openTikTok(v);else openYouTube(v);}
window.openVideo=openVideo;
document.querySelector("#closePlayer")?.addEventListener("click",closePlayer);modal?.addEventListener("click",e=>{if(e.target===modal)closePlayer()});document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!modal.hidden)closePlayer()});
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});
})();
